export const ADD_ID = "ADD_ID";
export const ADD_CONTENT = "ADD_CONTENT";
export const REMOVE_CONTENT = "REMOVE_CONTENT";
export const ADD_PROFILE_UP = "ADD_PROFILE_UP";
export const REMOVE_PROFILE_UP = "REMOVE_PROFILE_UP";

export const ADD_PROFILE_CENTER = "ADD_PROFILE_CENTER";
export const REMOVE_PROFILE_CENTER = "REMOVE_PROFILE_CENTER";
export const REMOVE_ITEM_PROFILE_CENTER = "REMOVE_ITEM_PROFILE_CENTER";
export const EDIT_ICON_PROFILE_CENTER = "EDIT_ICON_PROFILE_CENTER";

export const ADD_PROFILE_DOWN = "ADD_PROFILE_DOWN";
export const REMOVE_PROFILE_DOWN = "REMOVE_PROFILE_DOWN";
export const REMOVE_ITEM_PROFILE_DOWN = "REMOVE_ITEM_PROFILE_DOWN";
export const EDIT_ICON_PROFILE_DOWN = "EDIT_ICON_PROFILE_DOWN";

export const ADD_GRAPHICSNEN = "ADD_GRAPHICSNEN";
export const ADD_GRAPHICSNEN_COLOR = "ADD_GRAPHICSNEN_COLOR";
export const REMOVE_GRAPHICSNEN = "REMOVE_GRAPHICSNEN";
