export const ADD_CARD_SOCIAL = "ADD_CARD_SOCIAL";
export const ADD_CARD_LIKE_SOCIAL = "ADD_CARD_LIKE_SOCIAL";
export const ADD_CARD_COMMENT_SOCIAL = "ADD_CARD_COMMENT_SOCIAL";

export const REMOVE_CARD_SOCIAL = "REMOVE_CARD_SOCIAL";
